# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate numpy

Name:           rust-numpy0.23
Version:        0.23.0
Release:        1%{?dist}
Summary:        PyO3-based Rust bindings of the NumPy C-API

License:        BSD-2-Clause
URL:            https://crates.io/crates/numpy
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
# the numpy package needs to be present to run tests
BuildRequires: python3dist(numpy)

%global _description %{expand:
PyO3-based Rust bindings of the NumPy C-API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+half-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+half-devel %{_description}

This package contains library source intended for building other packages which
use the "half" feature of the "%{crate}" crate.

%files       -n %{name}+half-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nalgebra-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nalgebra-devel %{_description}

This package contains library source intended for building other packages which
use the "nalgebra" feature of the "%{crate}" crate.

%files       -n %{name}+nalgebra-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
