# Generated by rust2rpm 27
%bcond check 0
%global debug_package %{nil}

%global crate nalgebra

Name:           rust-nalgebra0.32
Version:        0.32.6
Release:        2%{?dist}
Summary:        General-purpose linear algebra library with transformations and statically-sized or dynamically-sized matrices

License:        BSD-3-Clause
URL:            https://crates.io/crates/nalgebra
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
General-purpose linear algebra library with transformations and
statically-sized or dynamically-sized matrices.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alga-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alga-devel %{_description}

This package contains library source intended for building other packages which
use the "alga" feature of the "%{crate}" crate.

%files       -n %{name}+alga-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bytemuck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bytemuck-devel %{_description}

This package contains library source intended for building other packages which
use the "bytemuck" feature of the "%{crate}" crate.

%files       -n %{name}+bytemuck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compare-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compare-devel %{_description}

This package contains library source intended for building other packages which
use the "compare" feature of the "%{crate}" crate.

%files       -n %{name}+compare-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-bytemuck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-bytemuck-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-bytemuck" feature of the "%{crate}" crate.

%files       -n %{name}+convert-bytemuck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam014-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam014-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam014" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam014-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam015-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam015-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam015" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam015-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam016-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam016-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam016" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam016-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam017-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam017-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam017" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam017-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam018-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam018-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam018" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam018-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam019-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam019-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam019" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam019-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam020-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam020-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam020" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam020-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam021-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam021-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam021" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam021-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam022-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam022-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam022" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam022-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam023-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam023-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam023" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam023-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam024-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam024-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam024" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam024-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam025-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam025-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam025" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam025-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-glam027-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-glam027-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-glam027" feature of the "%{crate}" crate.

%files       -n %{name}+convert-glam027-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+convert-mint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+convert-mint-devel %{_description}

This package contains library source intended for building other packages which
use the "convert-mint" feature of the "%{crate}" crate.

%files       -n %{name}+convert-mint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cuda-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cuda-devel %{_description}

This package contains library source intended for building other packages which
use the "cuda" feature of the "%{crate}" crate.

%files       -n %{name}+cuda-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cust_core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cust_core-devel %{_description}

This package contains library source intended for building other packages which
use the "cust_core" feature of the "%{crate}" crate.

%files       -n %{name}+cust_core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam014-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam014-devel %{_description}

This package contains library source intended for building other packages which
use the "glam014" feature of the "%{crate}" crate.

%files       -n %{name}+glam014-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam015-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam015-devel %{_description}

This package contains library source intended for building other packages which
use the "glam015" feature of the "%{crate}" crate.

%files       -n %{name}+glam015-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam016-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam016-devel %{_description}

This package contains library source intended for building other packages which
use the "glam016" feature of the "%{crate}" crate.

%files       -n %{name}+glam016-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam017-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam017-devel %{_description}

This package contains library source intended for building other packages which
use the "glam017" feature of the "%{crate}" crate.

%files       -n %{name}+glam017-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam018-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam018-devel %{_description}

This package contains library source intended for building other packages which
use the "glam018" feature of the "%{crate}" crate.

%files       -n %{name}+glam018-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam019-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam019-devel %{_description}

This package contains library source intended for building other packages which
use the "glam019" feature of the "%{crate}" crate.

%files       -n %{name}+glam019-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam020-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam020-devel %{_description}

This package contains library source intended for building other packages which
use the "glam020" feature of the "%{crate}" crate.

%files       -n %{name}+glam020-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam021-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam021-devel %{_description}

This package contains library source intended for building other packages which
use the "glam021" feature of the "%{crate}" crate.

%files       -n %{name}+glam021-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam022-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam022-devel %{_description}

This package contains library source intended for building other packages which
use the "glam022" feature of the "%{crate}" crate.

%files       -n %{name}+glam022-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam023-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam023-devel %{_description}

This package contains library source intended for building other packages which
use the "glam023" feature of the "%{crate}" crate.

%files       -n %{name}+glam023-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam024-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam024-devel %{_description}

This package contains library source intended for building other packages which
use the "glam024" feature of the "%{crate}" crate.

%files       -n %{name}+glam024-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam025-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam025-devel %{_description}

This package contains library source intended for building other packages which
use the "glam025" feature of the "%{crate}" crate.

%files       -n %{name}+glam025-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glam027-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glam027-devel %{_description}

This package contains library source intended for building other packages which
use the "glam027" feature of the "%{crate}" crate.

%files       -n %{name}+glam027-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+io-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+io-devel %{_description}

This package contains library source intended for building other packages which
use the "io" feature of the "%{crate}" crate.

%files       -n %{name}+io-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libm-devel %{_description}

This package contains library source intended for building other packages which
use the "libm" feature of the "%{crate}" crate.

%files       -n %{name}+libm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libm-force-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libm-force-devel %{_description}

This package contains library source intended for building other packages which
use the "libm-force" feature of the "%{crate}" crate.

%files       -n %{name}+libm-force-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macros-devel %{_description}

This package contains library source intended for building other packages which
use the "macros" feature of the "%{crate}" crate.

%files       -n %{name}+macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+matrixcompare-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+matrixcompare-core-devel %{_description}

This package contains library source intended for building other packages which
use the "matrixcompare-core" feature of the "%{crate}" crate.

%files       -n %{name}+matrixcompare-core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+matrixmultiply-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+matrixmultiply-devel %{_description}

This package contains library source intended for building other packages which
use the "matrixmultiply" feature of the "%{crate}" crate.

%files       -n %{name}+matrixmultiply-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mint-devel %{_description}

This package contains library source intended for building other packages which
use the "mint" feature of the "%{crate}" crate.

%files       -n %{name}+mint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nalgebra-macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nalgebra-macros-devel %{_description}

This package contains library source intended for building other packages which
use the "nalgebra-macros" feature of the "%{crate}" crate.

%files       -n %{name}+nalgebra-macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pest-devel %{_description}

This package contains library source intended for building other packages which
use the "pest" feature of the "%{crate}" crate.

%files       -n %{name}+pest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pest_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pest_derive-devel %{_description}

This package contains library source intended for building other packages which
use the "pest_derive" feature of the "%{crate}" crate.

%files       -n %{name}+pest_derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proptest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proptest-devel %{_description}

This package contains library source intended for building other packages which
use the "proptest" feature of the "%{crate}" crate.

%files       -n %{name}+proptest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+proptest-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+proptest-support-devel %{_description}

This package contains library source intended for building other packages which
use the "proptest-support" feature of the "%{crate}" crate.

%files       -n %{name}+proptest-support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+quickcheck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quickcheck-devel %{_description}

This package contains library source intended for building other packages which
use the "quickcheck" feature of the "%{crate}" crate.

%files       -n %{name}+quickcheck-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages which
use the "rand" feature of the "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-no-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-no-std-devel %{_description}

This package contains library source intended for building other packages which
use the "rand-no-std" feature of the "%{crate}" crate.

%files       -n %{name}+rand-no-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-package-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-package-devel %{_description}

This package contains library source intended for building other packages which
use the "rand-package" feature of the "%{crate}" crate.

%files       -n %{name}+rand-package-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand_distr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand_distr-devel %{_description}

This package contains library source intended for building other packages which
use the "rand_distr" feature of the "%{crate}" crate.

%files       -n %{name}+rand_distr-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-safe-deser-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-safe-deser-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv-safe-deser" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-safe-deser-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv-serialize" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rkyv-serialize-no-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rkyv-serialize-no-std-devel %{_description}

This package contains library source intended for building other packages which
use the "rkyv-serialize-no-std" feature of the "%{crate}" crate.

%files       -n %{name}+rkyv-serialize-no-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "serde-serialize" feature of the "%{crate}" crate.

%files       -n %{name}+serde-serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-serialize-no-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-serialize-no-std-devel %{_description}

This package contains library source intended for building other packages which
use the "serde-serialize-no-std" feature of the "%{crate}" crate.

%files       -n %{name}+serde-serialize-no-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+slow-tests-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+slow-tests-devel %{_description}

This package contains library source intended for building other packages which
use the "slow-tests" feature of the "%{crate}" crate.

%files       -n %{name}+slow-tests-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sparse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sparse-devel %{_description}

This package contains library source intended for building other packages which
use the "sparse" feature of the "%{crate}" crate.

%files       -n %{name}+sparse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jan 03 2025 Alexander F. Lent <lx@xanderlent.com> - 0.32.6-1
- Initial package
