# Generated by rust2rpm 27
%bcond check 0
# check=1 requires criterion, creating a circular dep
%global debug_package %{nil}

%global crate gif

Name:           rust-gif0.12
Version:        0.12.0
Release:        1%{?dist}
Summary:        De- and encoder

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/gif
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
GIF de- and encoder.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/Changes.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+color_quant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color_quant-devel %{_description}

This package contains library source intended for building other packages which
use the "color_quant" feature of the "%{crate}" crate.

%files       -n %{name}+color_quant-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+raii_no_panic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+raii_no_panic-devel %{_description}

This package contains library source intended for building other packages which
use the "raii_no_panic" feature of the "%{crate}" crate.

%files       -n %{name}+raii_no_panic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jan 03 2025 Alexander F. Lent <lx@xanderlent.com> - 0.12.0-1
- Initial package
