# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate macro_rules_attribute

Name:           rust-macro_rules_attribute
Version:        0.2.0
Release:        1%{?dist}
Summary:        Use declarative macros in attribute or derive position

License:        MIT
URL:            https://crates.io/crates/macro_rules_attribute
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Use declarative macros in attribute or derive position.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/LICENSE-ZLIB
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+better-docs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+better-docs-devel %{_description}

This package contains library source intended for building other packages which
use the "better-docs" feature of the "%{crate}" crate.

%files       -n %{name}+better-docs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+verbose-expansions-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+verbose-expansions-devel %{_description}

This package contains library source intended for building other packages which
use the "verbose-expansions" feature of the "%{crate}" crate.

%files       -n %{name}+verbose-expansions-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 02 2025 Alexander F. Lent <lx@xanderlent.com> - 0.2.0-1
- Initial package
