# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate esaxx-rs

Name:           rust-esaxx-rs
Version:        0.1.10
Release:        2%{?dist}
Summary:        Wrapping around sentencepiece's esaxxx library

License:        Apache-2.0
URL:            https://crates.io/crates/esaxx-rs
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          esaxx-rs-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Wrapping around sentencepiece's esaxxx library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cc-devel %{_description}

This package contains library source intended for building other packages which
use the "cc" feature of the "%{crate}" crate.

%files       -n %{name}+cc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cpp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cpp-devel %{_description}

This package contains library source intended for building other packages which
use the "cpp" feature of the "%{crate}" crate.

%files       -n %{name}+cpp-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 06 2025 Alexander F. Lent <lx@xanderlent.com> - 0.1.10-2
- Patch out criterion dev-dependency
* Thu Jan 02 2025 Alexander F. Lent <lx@xanderlent.com> - 0.1.10-1
- Initial package
